import { initDb } from '../src/server/db.js';
import { parseSshOutput } from '../src/server/poller.js';
import assert from 'assert';

async function runTests() {
  console.log('--- STARTING SYSTEM UNIT TESTS ---');

  // Test 1: Database schemas initialization
  try {
    await initDb();
    console.log('   TEST 1 PASSED: Database initialized successfully');
  } catch (err) {
    console.error('❌ TEST 1 FAILED: DB initialization error', err);
    process.exit(1);
  }

  // Test 2: Metrics Parser Validation
  try {
    // Mock the SSH output generated by the composite command
    const mockSshOutput = `
===MEMINFO===
MemTotal:       16384000 kB
MemAvailable:    8192000 kB
===UPTIME===
172800.45 342934.34
===DISK===
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/sda1       40000000  10000000  30000000  25% /
===CPU===
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  0      0 500000  20000  40000    0    0     1    12   50   60  5  2 88  5  0
===OS===
NAME="Ubuntu"
VERSION="22.04 LTS"
PRETTY_NAME="Ubuntu 22.04 LTS"
`;

    const metrics = parseSshOutput(mockSshOutput);

    // Verify CPU Load: 100 - idle (88) = 12%
    assert.strictEqual(metrics.cpu, 12, 'CPU load calculation incorrect');

    // Verify RAM calculations
    assert.strictEqual(metrics.ram.percent, 50, 'RAM usage percent incorrect');
    assert.strictEqual(metrics.ram.total, 16384000 * 1024, 'RAM total bytes incorrect');
    assert.strictEqual(metrics.ram.used, 8192000 * 1024, 'RAM used bytes incorrect');

    // Verify Disk calculations
    assert.strictEqual(metrics.disk.percent, 25, 'Disk usage percent incorrect');
    assert.strictEqual(metrics.disk.total, 40000000 * 1024, 'Disk total bytes incorrect');
    assert.strictEqual(metrics.disk.used, 10000000 * 1024, 'Disk used bytes incorrect');

    // Verify Uptime: parsed float rounded is 172800
    assert.strictEqual(metrics.uptime, 172800, 'Uptime parsing incorrect');

    // Verify OS name extraction
    assert.strictEqual(metrics.os, 'Ubuntu 22.04 LTS', 'OS name extraction incorrect');

    console.log('   TEST 2 PASSED: SSH VM Command metrics parser assertions match expected values.');
  } catch (err) {
    console.error('❌ TEST 2 FAILED:', err.message);
    process.exit(1);
  }

  console.log('✅ ALL UNIT TESTS COMPLETED SUCCESSFULLY ✅');
  process.exit(0);
}

runTests();
